/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tree;

import java.awt.Canvas;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Administrator
 */
public class Tree_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Tree_Frame
     */
    public Tree_Frame() {
        super("树");
        initComponents();
        jLabel1.setVisible(false);
        jTextField1.setVisible(false);
        jButton1.setVisible(false);
        this.setBounds(100, 100, 600, 500);
        int a[] = {12,78,45,8,6};
        for(int i=0;i<a.length;i++)
            c6.insert_Tree(a[i]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("工具箱");
        DefaultMutableTreeNode rt1 = new DefaultMutableTreeNode("显示");
        DefaultMutableTreeNode rt2 = new DefaultMutableTreeNode("插入");
        DefaultMutableTreeNode rt3 = new DefaultMutableTreeNode("删除");
        DefaultMutableTreeNode rt4 = new DefaultMutableTreeNode("最大值");
        DefaultMutableTreeNode rt5 = new DefaultMutableTreeNode("最小值");
        DefaultMutableTreeNode rt6 = new DefaultMutableTreeNode("前驱");
        DefaultMutableTreeNode rt7 = new DefaultMutableTreeNode("后继");
        root.add(rt1);
        root.add(rt2);
        root.add(rt3);
        root.add(rt4);
        root.add(rt5);
        root.add(rt6);
        root.add(rt7);
        root1 = rt1;
        root2 = rt2;
        root3 = rt3;
        root4 = rt4;
        root5 = rt5;
        root6 = rt6;
        root7 = rt7;
        DefaultMutableTreeNode rt8 = new DefaultMutableTreeNode("退出");
        root.add(rt8);
        root8 = rt8;
        jTree1 = new javax.swing.JTree(root);
        jPanel1 = new javax.swing.JPanel();
        canvas1 = new Mycanvas();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jButton1.setText("确定");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(177, 177, 177))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    class Mycanvas extends Canvas{
         public void paint(Graphics g){
        c6.walk_Tree(0);
        System.out.println();
        Graphics2D g2d = (Graphics2D)g;
         int r = 14;
         int x = c6.get(c6.pv, 0).x;
         int y = c6.get(c6.pv, 0).y;
         g2d.drawOval(x-r, y-r, 2*r, 2*r);
         g2d.drawString(c6.get(c6.pv, 0).data+"", x, y);
         if(iflag==0){
             g2d.setColor(Color.red);
             g2d.fillOval(x-r, y-r, 2*r, 2*r);
         }
         g2d.setColor(Color.black);
         for(int i=1;i<c6.pv.size();i++){
             x = c6.get(c6.pv, i).x;
             y = c6.get(c6.pv, i).y;
             if(x!=0&&y!=0){
                int px = c6.get(c6.pv,c6.get(c6.pv, i).p).x;
                int py = c6.get(c6.pv,c6.get(c6.pv, i).p).y;
                g2d.drawOval(x-r, y-r, 2*r, 2*r);
                g2d.draw(new Line2D.Double(x,y-r,px,py+r));
                if(iflag==i){
                    g2d.setColor(Color.red);
                    g2d.fillOval(x-r, y-r, 2*r, 2*r);
                }
                g2d.setColor(Color.black);
                g2d.drawString(c6.get(c6.pv, i).data+"", x, y);
                
             }
         }
         iflag = -1;
    }
    }
    
    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        // TODO add your handling code here:
         DefaultMutableTreeNode node = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
        if (node.equals(root1)){
            jLabel1.setVisible(false);
            jTextField1.setVisible(false);
            jButton1.setVisible(false);
            canvas1.repaint();
        }
        else if (node.equals(root2)){
            jLabel1.setText("请输入数据 ：");
            jLabel1.setVisible(true);
            jTextField1.setVisible(true);
            jButton1.setVisible(true);
            flag = 1;
        }
        else if (node.equals(root3)){
            jLabel1.setText("请输入数据 ：");
            jLabel1.setVisible(true);
            jTextField1.setVisible(true);
            jButton1.setVisible(true);
            flag = 2;
        }
        else if (node.equals(root4)){
            jLabel1.setVisible(false);
            jTextField1.setVisible(false);
            jButton1.setVisible(false);
            iflag = c6.max_Tree1(0);
            canvas1.repaint();
            flag = 3;
        }
        else if (node.equals(root5)){
            jLabel1.setVisible(false);
            jTextField1.setVisible(false);
            jButton1.setVisible(false);
            iflag = c6.min_Tree1(0);
            canvas1.repaint();
            flag = 4;
        }
        else if (node.equals(root6)){
            jLabel1.setText("请输入数据 ：");
            jLabel1.setVisible(true);
            jTextField1.setVisible(true);
            jButton1.setVisible(true);
            flag = 6;
        }
        else if (node.equals(root7)){
            jLabel1.setText("请输入数据 ：");
            jLabel1.setVisible(true);
            jTextField1.setVisible(true);
            jButton1.setVisible(true);
            flag = 7;
        }
        else if (node.equals(root8)){
            System.exit(0);
        }
       
    }//GEN-LAST:event_jTree1ValueChanged
    boolean can_Do(){
        if(jTextField1.getText().trim().matches("[0-9]+"))
            return true;
        JOptionPane.showMessageDialog(null,  "数据不规范！","提示", JOptionPane.WARNING_MESSAGE);            
        return false;
    } 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(flag==1&&can_Do()){
            String ss = jTextField1.getText().trim();
            int e = Integer.parseInt(ss);
            iflag = c6.insert_Tree(e);
            canvas1.repaint();
        }
        if(flag==2&&can_Do()){
            String ss = jTextField1.getText().trim();
            int e = Integer.parseInt(ss);
            c6.delete_Tree(e);
            canvas1.repaint();
        }
        if(flag==6&&can_Do()){
            String ss = jTextField1.getText().trim();
            int e = Integer.parseInt(ss);
            iflag = c6.precursor_Tree(e);
            canvas1.repaint();
        }
        if(flag==7&&can_Do()){
            String ss = jTextField1.getText().trim();
            int e = Integer.parseInt(ss);
            iflag = c6.Successor_Tree(e);
            canvas1.repaint();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tree_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tree_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tree_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tree_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tree_Frame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
    DefaultMutableTreeNode root1,root2,root3,root4,root5,root6,root7,root8;
    Tree_fun c6 = new Tree_fun();
    int flag = 0,iflag = -1;
}
